(() => {
'use strict';

const $ = id => document.getElementById(id);
const $$ = sel => [...document.querySelectorAll(sel)];
const STORAGE_KEY='tickrift-v5-state';
const SETTINGS_KEY='tickrift-v5-settings';
const FEE_RATE=0.0004;
const SLIPPAGE=0.00012;
const COLORS=['#7aa2f7','#35c58a','#e8bf62','#a78bfa','#f58a65','#6cc7d9','#d984c6','#a7b36b','#d0d6de'];
const CG_BASE='https://api.coingecko.com/api/v3';

const ASSETS={
  stocks:[
    A('NVDA','NVIDIA','NASDAQ','USD',178,.012,'Stock'),A('AAPL','Apple','NASDAQ','USD',238,.006,'Stock'),A('MSFT','Microsoft','NASDAQ','USD',516,.005,'Stock'),A('AMZN','Amazon','NASDAQ','USD',214,.007,'Stock'),A('META','Meta Platforms','NASDAQ','USD',666,.008,'Stock'),A('GOOGL','Alphabet','NASDAQ','USD',205,.006,'Stock'),A('TSLA','Tesla','NASDAQ','USD',369,.014,'Stock'),A('AMD','Advanced Micro Devices','NASDAQ','USD',211,.011,'Stock'),A('ASML','ASML Holding','NASDAQ','USD',1418,.008,'Stock'),A('JPM','JPMorgan Chase','NYSE','USD',312,.005,'Stock'),
    A('NFLX','Netflix','NASDAQ','USD',1190,.009,'Stock'),A('AVGO','Broadcom','NASDAQ','USD',338,.008,'Stock'),A('ORCL','Oracle','NYSE','USD',238,.007,'Stock'),A('CRM','Salesforce','NYSE','USD',252,.007,'Stock'),A('INTC','Intel','NASDAQ','USD',39,.011,'Stock'),A('QCOM','Qualcomm','NASDAQ','USD',178,.009,'Stock'),A('PLTR','Palantir','NASDAQ','USD',159,.013,'Stock'),A('KO','Coca-Cola','NYSE','USD',69,.003,'Stock'),A('DIS','Walt Disney','NYSE','USD',118,.006,'Stock'),A('NKE','Nike','NYSE','USD',73,.008,'Stock'),
    A('BA','Boeing','NYSE','USD',223,.009,'Stock'),A('LLY','Eli Lilly','NYSE','USD',760,.007,'Stock'),A('UNH','UnitedHealth','NYSE','USD',352,.008,'Stock'),A('XOM','Exxon Mobil','NYSE','USD',114,.005,'Stock'),A('WMT','Walmart','NASDAQ','USD',103,.004,'Stock'),A('COST','Costco','NASDAQ','USD',948,.005,'Stock'),A('V','Visa','NYSE','USD',349,.004,'Stock'),A('MA','Mastercard','NYSE','USD',586,.004,'Stock'),A('UBER','Uber','NYSE','USD',91,.008,'Stock'),A('SHOP','Shopify','NASDAQ','USD',149,.010,'Stock')
  ],
  crypto:[
    C('BTC','Bitcoin','bitcoin',115000,.011),C('ETH','Ethereum','ethereum',4400,.013),C('SOL','Solana','solana',236,.017),C('XRP','XRP','ripple',3.08,.015),C('BNB','BNB','binancecoin',998,.011),C('ADA','Cardano','cardano',.91,.016),C('DOGE','Dogecoin','dogecoin',.267,.019),C('AVAX','Avalanche','avalanche-2',31,.018),C('LINK','Chainlink','chainlink',24,.016),C('DOT','Polkadot','polkadot',4.1,.017),C('LTC','Litecoin','litecoin',118,.014),C('BCH','Bitcoin Cash','bitcoin-cash',585,.016)
  ],
  indices:[
    A('SPX','S&P 500 Index','INDEX','USD',6710,.0028,'Index'),A('NDX','Nasdaq-100 Index','INDEX','USD',24785,.0036,'Index'),A('DJI','Dow Jones Industrial Average','INDEX','USD',46880,.0023,'Index'),A('RUT','Russell 2000 Index','INDEX','USD',2488,.0041,'Index'),A('AEX','AEX Index','EURONEXT','EUR',918,.0030,'Index'),A('DAX','DAX Index','XETRA','EUR',23874,.0031,'Index'),A('FTSE','FTSE 100 Index','LSE','GBP',9280,.0024,'Index'),A('N225','Nikkei 225','JPX','JPY',44700,.0034,'Index'),A('STOXX50E','Euro Stoxx 50','INDEX','EUR',5460,.0028,'Index')
  ],
  funds:[
    A('SPY','SPDR S&P 500 ETF Trust','NYSE ARCA','USD',668,.0030,'ETF'),A('QQQ','Invesco QQQ Trust','NASDAQ','USD',603,.0037,'ETF'),A('VOO','Vanguard S&P 500 ETF','NYSE ARCA','USD',616,.0030,'ETF'),A('VTI','Vanguard Total Stock Market ETF','NYSE ARCA','USD',325,.0029,'ETF'),A('IWM','iShares Russell 2000 ETF','NYSE ARCA','USD',247,.0042,'ETF'),A('DIA','SPDR Dow Jones Industrial Average ETF','NYSE ARCA','USD',468,.0025,'ETF'),A('GLD','SPDR Gold Shares','NYSE ARCA','USD',345,.0040,'ETF'),A('TLT','iShares 20+ Year Treasury Bond ETF','NASDAQ','USD',89,.0035,'ETF'),A('XLK','Technology Select Sector SPDR Fund','NYSE ARCA','USD',282,.0040,'ETF'),A('XLF','Financial Select Sector SPDR Fund','NYSE ARCA','USD',54,.0033,'ETF'),A('VWRL','Vanguard FTSE All-World UCITS ETF','LSE','USD',151,.0024,'ETF'),A('VWCE','Vanguard FTSE All-World UCITS ETF','XETRA','EUR',141,.0024,'ETF'),A('CSPX','iShares Core S&P 500 UCITS ETF','LSE','USD',682,.0030,'ETF')
  ]
};
function A(s,n,ex,c,p,vol,type){return {s,n,ex,c,p,vol,type,provider:s};}
function C(s,n,cgid,p,vol){return {s,n,ex:'CRYPTO',c:'USD',p,vol,type:'Crypto',provider:`${s}/USD`,cgid};}
const ALL=Object.values(ASSETS).flat();
const BY=Object.fromEntries(ALL.map(a=>[a.s,a]));

const defaults={
  cash:100000,startBalance:100000,realized:0,positions:[],holdings:[],orders:[],history:[],journal:[],recurring:[],equityHistory:[{t:Date.now(),v:100000}],watchlist:['NVDA','AAPL','MSFT','BTC','ETH','SPX','SPY'],
  category:'stocks',symbol:'NVDA',view:'home',mode:'trade',tradeSide:'long',investSide:'buy',tradeOrderType:'market',investOrderType:'market',tutorialSeen:false
};
const settingDefaults={theme:'carbon',up:'#35c58a',down:'#ef5f72',grid:true,crosshair:true,compact:false,chartType:'candles',timeframe:'5m',bars:96,indicators:{volume:true,sma:false,sma50:false,ema:false,vwap:false,bb:false,rsi:false,macd:false}};
const state=Object.assign(structuredClone(defaults),load(STORAGE_KEY,{}));
for(const k of ['positions','holdings','orders','history','journal','recurring','equityHistory','watchlist']) if(!Array.isArray(state[k])) state[k]=structuredClone(defaults[k]);
const settings=deepMerge(structuredClone(settingDefaults),load(SETTINGS_KEY,{}));
const series={};
const sourceState={};
let selected=BY[state.symbol]||ASSETS.stocks[0];
let activePane='positions';
let watchlistOnly=false;
let hoverIndex=null;
let tutorialStep=0;
let externalEndpoint='';
let liveTimer=null,externalTimer=null,cryptoTimer=null;
let lastEquitySample=Date.now();
let depletedShown=false;

ALL.forEach(a=>{series[a.s]=generateSeries(a,320);sourceState[a.s]={mode:'demo',source:'Simulation',updated:Date.now(),delay:null};});

function load(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}
function deepMerge(t,s){if(!s||typeof s!=='object')return t;for(const k of Object.keys(s)){if(s[k]&&typeof s[k]==='object'&&!Array.isArray(s[k]))t[k]=deepMerge(t[k]||{},s[k]);else t[k]=s[k];}return t;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function randn(){let u=0,v=0;while(!u)u=Math.random();while(!v)v=Math.random();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function money(v,c='USD'){const d=Math.abs(v)<1?4:2;try{return new Intl.NumberFormat('en-US',{style:'currency',currency:c,minimumFractionDigits:d,maximumFractionDigits:d}).format(v)}catch{return '$'+Number(v).toFixed(2)}}
function price(v,c=selected.c){if(c==='EUR')return new Intl.NumberFormat('en-US',{style:'currency',currency:'EUR',maximumFractionDigits:v<1?4:2}).format(v);if(c==='GBP')return new Intl.NumberFormat('en-US',{style:'currency',currency:'GBP',maximumFractionDigits:v<1?4:2}).format(v);if(c==='JPY')return new Intl.NumberFormat('en-US',{style:'currency',currency:'JPY',maximumFractionDigits:2}).format(v);if(v>=10000)return '$'+v.toLocaleString('en-US',{maximumFractionDigits:2});if(v<1)return '$'+v.toFixed(4);return '$'+v.toFixed(2)}
function num(v){if(!Number.isFinite(v))return '—';if(v>=1e9)return(v/1e9).toFixed(1)+'B';if(v>=1e6)return(v/1e6).toFixed(1)+'M';if(v>=1e3)return(v/1e3).toFixed(1)+'K';return Math.round(v).toString()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function cap(s){return s.charAt(0).toUpperCase()+s.slice(1)}
function categoryFor(a){return Object.keys(ASSETS).find(k=>ASSETS[k].includes(a))||'stocks'}
function currentPrice(s=selected.s){return series[s]?.at(-1)?.c??BY[s]?.p??0}
function currentHolding(s){return state.holdings.find(h=>h.symbol===s)}

function generateSeries(a,count=320){
  const out=[];let p=a.p*(.94+Math.random()*.1),t=Date.now()-count*300000;
  for(let i=0;i<count;i++){const o=p,dr=randn()*a.vol*.28+Math.sin(i/29)*a.vol*.025,c=Math.max(.00001,o*(1+dr)),wick=Math.abs(randn())*a.vol*.17,h=Math.max(o,c)*(1+wick),l=Math.min(o,c)*(1-wick*.9),v=Math.round(50000+(Math.random()**2)*3800000);out.push({t:t+i*300000,o,h,l,c,v});p=c;}
  const scale=a.p/out.at(-1).c;out.forEach(d=>{d.o*=scale;d.h*=scale;d.l*=scale;d.c*=scale});return out;
}

function dayStats(a=selected){const d=series[a.s]||[];if(!d.length)return {open:0,high:0,low:0,vol:0,change:0,high52:0,low52:0};const slice=d.slice(-78),last=d.at(-1),prev=d[Math.max(0,d.length-79)]||slice[0];return{open:slice[0].o,high:Math.max(...slice.map(x=>x.h)),low:Math.min(...slice.map(x=>x.l)),vol:slice.reduce((s,x)=>s+(x.v||0),0),change:(last.c-prev.c)/prev.c*100,high52:Math.max(...d.map(x=>x.h))*1.07,low52:Math.min(...d.map(x=>x.l))*.88};}
function tradePnl(p){const dir=p.side==='long'?1:-1;return(currentPrice(p.symbol)-p.entry)*p.qty*dir;}
function holdPnl(h){return(currentPrice(h.symbol)-h.avg)*h.qty;}
function holdValue(h){return currentPrice(h.symbol)*h.qty;}
function metrics(){const tradeUnreal=state.positions.reduce((s,p)=>s+tradePnl(p),0),investValue=state.holdings.reduce((s,h)=>s+holdValue(h),0),investedCost=state.holdings.reduce((s,h)=>s+h.avg*h.qty,0),investUnreal=state.holdings.reduce((s,h)=>s+holdPnl(h),0),reserved=state.positions.reduce((s,p)=>s+p.margin,0);return{tradeUnreal,investValue,investedCost,investUnreal,reserved,equity:state.cash+reserved+tradeUnreal+investValue};}

function init(){
  applySettings();bind();populateJournal();renderAll();setupCanvases();startFeeds();
  liveTimer=setInterval(tick,1200);
  if(!state.tutorialSeen)setTimeout(()=>openTutorial(0),900);
}
function bind(){
  $$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
  $('tutorialNav').onclick=()=>openTutorial(0);$('openTutorialHome').onclick=()=>openTutorial(0);$('openTutorialSettings').onclick=()=>{closeSettings();openTutorial(0)};
  $('startTradeHome').onclick=()=>enterMode('trade');$('modeCardTrade').onclick=()=>enterMode('trade');$('startInvestHome').onclick=()=>enterMode('invest');$('modeCardInvest').onclick=()=>enterMode('invest');
  $$('.asset-tabs button').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;watchlistOnly=false;$('watchlistOnly').classList.remove('active');renderWatchlist();save()});
  $('assetSearch').oninput=renderWatchlist;$('watchlistOnly').onclick=()=>{watchlistOnly=!watchlistOnly;$('watchlistOnly').classList.toggle('active',watchlistOnly);renderWatchlist()};
  $('favoriteAsset').onclick=toggleFavorite;
  $$('#modeSwitch button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
  $$('#directionToggle button').forEach(b=>b.onclick=()=>{state.tradeSide=b.dataset.side;renderTicket();save()});
  $$('#investSideToggle button').forEach(b=>b.onclick=()=>{state.investSide=b.dataset.side;renderTicket();save()});
  $$('#tradeOrderTypes button').forEach(b=>b.onclick=()=>{state.tradeOrderType=b.dataset.type;renderTicket();save()});
  $$('#investOrderTypes button').forEach(b=>b.onclick=()=>{state.investOrderType=b.dataset.type;renderTicket();save()});
  ['tradeAmount','tradeLeverage','tradeTrigger','investAmount','investTrigger','slValue','tpValue','trailValue','recurringAmount'].forEach(id=>$(id).addEventListener('input',renderTicketNumbers));
  ['slEnabled','tpEnabled','trailEnabled'].forEach(id=>$(id).onchange=()=>{const map={slEnabled:'slValue',tpEnabled:'tpValue',trailEnabled:'trailValue'};$(map[id]).disabled=!$(id).checked;renderTicketNumbers()});
  $('recurringEnabled').onchange=()=>{$('recurringFields').classList.toggle('hidden',!$('recurringEnabled').checked)};
  $$('#tradeQuick button').forEach(b=>b.onclick=()=>{$('tradeAmount').value=b.dataset.value;renderTicketNumbers()});
  $$('#investQuick button').forEach(b=>b.onclick=()=>{$('investAmount').value=b.dataset.value;renderTicketNumbers()});
  $('tradeSubmit').onclick=placeTrade;$('investSubmit').onclick=placeInvestment;
  $$('#timeframes button').forEach(b=>b.onclick=async()=>{settings.timeframe=b.dataset.tf;applySettings();await loadSelectedMarketHistory();drawChart();save()});
  $('chartType').onchange=()=>{settings.chartType=$('chartType').value;drawChart();save()};
  $$('#indicatorBar button[data-ind]').forEach(b=>b.onclick=()=>{const k=b.dataset.ind;settings.indicators[k]=!settings.indicators[k];applySettings();drawChart();save()});
  $('zoomIn').onclick=()=>{settings.bars=clamp(settings.bars-16,32,220);drawChart();save()};$('zoomOut').onclick=()=>{settings.bars=clamp(settings.bars+16,32,220);drawChart();save()};$('fitChart').onclick=()=>{settings.bars=96;drawChart();save()};
  $$('#activityTabs button').forEach(b=>b.onclick=()=>{activePane=b.dataset.pane;renderActivity()});
  $('settingsButton').onclick=openSettings;$('closeSettings').onclick=closeSettings;$('settingsBackdrop').onclick=e=>{if(e.target===$('settingsBackdrop'))closeSettings()};
  $$('#themePresets button').forEach(b=>b.onclick=()=>{settings.theme=b.dataset.theme;applySettings();drawChart();renderPortfolioCharts();save()});
  $('upColor').oninput=()=>{settings.up=$('upColor').value;applySettings();drawChart();save()};$('downColor').oninput=()=>{settings.down=$('downColor').value;applySettings();drawChart();save()};
  $('gridToggle').onchange=()=>{settings.grid=$('gridToggle').checked;drawChart();save()};$('crosshairToggle').onchange=()=>{settings.crosshair=$('crosshairToggle').checked;drawChart();save()};$('compactToggle').onchange=()=>{settings.compact=$('compactToggle').checked;applySettings();save()};
  $('resetSimulation').onclick=()=>resetAccount(100000,true);
  $('saveJournal').onclick=saveJournal;$('clearJournal').onclick=()=>{if(confirm('Clear every journal entry?')){state.journal=[];renderJournal();save()}};
  $('closeTutorial').onclick=closeTutorial;$('tutorialPrev').onclick=()=>{tutorialStep=Math.max(0,tutorialStep-1);renderTutorial()};$('tutorialNext').onclick=()=>{if(tutorialStep>=TUTORIAL.length-1){closeTutorial();state.tutorialSeen=true;save()}else{tutorialStep++;renderTutorial()}};$('tutorialOverlay').onclick=e=>{if(e.target===$('tutorialOverlay'))closeTutorial()};
  $('restart100').onclick=()=>resetAccount(100000,false);$('restart10').onclick=()=>resetAccount(10000,false);$('closeDepleted').onclick=()=>$('depletedOverlay').classList.add('hidden');
  $('chartCanvas').addEventListener('mousemove',chartHover);$('chartCanvas').addEventListener('mouseleave',()=>{hoverIndex=null;$('crosshairInfo').classList.add('hidden');drawChart()});
  window.addEventListener('resize',()=>{setupCanvases();drawChart();drawHeroChart();renderPortfolioCharts()});
}
function enterMode(mode){setMode(mode);setView('terminal');setTimeout(()=>{setupCanvases();drawChart()},50)}
function setView(v){if(!['home','terminal','portfolio','journal'].includes(v))return;state.view=v;$$('.view').forEach(x=>x.classList.remove('active'));$(v+'View').classList.add('active');$$('.nav-link[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='terminal')setTimeout(()=>{setupCanvases();drawChart()},20);if(v==='portfolio')setTimeout(()=>{setupCanvases();renderPortfolioCharts()},20);if(v==='home')setTimeout(()=>{setupCanvases();drawHeroChart()},20);save();}
function setMode(m){state.mode=m;renderTicket();save()}
function openSettings(){$('settingsBackdrop').classList.remove('hidden')}
function closeSettings(){$('settingsBackdrop').classList.add('hidden')}
function applySettings(){document.body.classList.remove('theme-slate','theme-midnight','compact');if(settings.theme==='slate')document.body.classList.add('theme-slate');if(settings.theme==='midnight')document.body.classList.add('theme-midnight');if(settings.compact)document.body.classList.add('compact');document.documentElement.style.setProperty('--up',settings.up);document.documentElement.style.setProperty('--down',settings.down);$('upColor').value=settings.up;$('downColor').value=settings.down;$('gridToggle').checked=settings.grid;$('crosshairToggle').checked=settings.crosshair;$('compactToggle').checked=settings.compact;$('chartType').value=settings.chartType;$$('#themePresets button').forEach(b=>b.classList.toggle('active',b.dataset.theme===settings.theme));$$('#timeframes button').forEach(b=>b.classList.toggle('active',b.dataset.tf===settings.timeframe));$$('#indicatorBar button[data-ind]').forEach(b=>b.classList.toggle('active',!!settings.indicators[b.dataset.ind]));}

function renderAll(){renderHeader();renderHome();renderWatchlist();renderInstrument();renderAccount();renderTicket();renderActivity();renderPortfolio();renderJournal();setupCanvases();drawChart();drawHeroChart();}
function renderHeader(){const m=metrics();$('headerEquity').textContent=money(m.equity);const modes=Object.values(sourceState).map(x=>x.mode);const live=modes.filter(x=>x==='live').length,delayed=modes.filter(x=>x==='delayed').length;const pill=$('globalFeedPill');pill.classList.remove('live','mixed');if(live===ALL.length){pill.classList.add('live');$('globalFeedLabel').textContent='MARKET DATA'}else if(live||delayed){pill.classList.add('mixed');$('globalFeedLabel').textContent='MIXED DATA'}else{$('globalFeedLabel').textContent='SIMULATION'} }
function renderHome(){const picks=['NVDA','AAPL','BTC','ETH','SPX'];$('heroMarketList').innerHTML=picks.map(s=>{const a=BY[s],st=dayStats(a),src=sourceState[s];return `<div class="hero-market-row"><button data-hero-symbol="${s}"><strong>${s}</strong><small>${escapeHtml(a.n)}</small></button><span class="hero-price">${price(currentPrice(s),a.c)}</span><span class="hero-change ${st.change>=0?'positive':'negative'}">${st.change>=0?'+':''}${st.change.toFixed(2)}%</span></div>`}).join('');$$('[data-hero-symbol]').forEach(b=>b.onclick=()=>{selectAsset(b.dataset.heroSymbol);setView('terminal')});const marketLinked=picks.some(s=>sourceState[s].mode!=='demo');$('heroDataChip').textContent=marketLinked?'MIXED / MARKET-LINKED':'SIMULATED';$('heroDataChip').classList.toggle('live',marketLinked);$('heroSelected').textContent=`${selected.s} · ${selected.n}`;}
function renderWatchlist(){const q=$('assetSearch').value.trim().toLowerCase(),list=watchlistOnly?ALL.filter(a=>state.watchlist.includes(a.s)):ASSETS[state.category];const filtered=list.filter(a=>!q||a.s.toLowerCase().includes(q)||a.n.toLowerCase().includes(q));$('assetCount').textContent=`${filtered.length} instrument${filtered.length===1?'':'s'}`;$$('.asset-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.category===state.category));$('watchlist').innerHTML=filtered.map(a=>{const st=dayStats(a);return `<div class="asset-row ${a.s===selected.s?'active':''}"><button data-symbol="${a.s}"><strong>${a.s}</strong><small>${escapeHtml(a.n)}</small></button><div class="asset-quote"><b>${price(currentPrice(a.s),a.c)}</b><span class="${st.change>=0?'positive':'negative'}">${st.change>=0?'+':''}${st.change.toFixed(2)}%</span></div></div>`}).join('')||'<div class="empty-state">No instruments found</div>';$$('[data-symbol]').forEach(b=>b.onclick=()=>selectAsset(b.dataset.symbol));}
async function selectAsset(s){if(!BY[s])return;selected=BY[s];state.symbol=s;state.category=categoryFor(selected);$('assetSearch').value='';await loadSelectedMarketHistory();renderAll();save();}
function toggleFavorite(){const i=state.watchlist.indexOf(selected.s);if(i>=0)state.watchlist.splice(i,1);else state.watchlist.push(selected.s);renderInstrument();renderWatchlist();save();}
function renderInstrument(){const a=selected,st=dayStats(a),src=sourceState[a.s];$('symbolLabel').textContent=a.s;$('nameLabel').textContent=a.n;$('assetTypeBadge').textContent=a.type.toUpperCase();$('exchangeLabel').textContent=a.ex;$('currencyLabel').textContent=a.c;$('priceLabel').textContent=price(currentPrice(a.s),a.c);$('changeLabel').textContent=(st.change>=0?'+':'')+st.change.toFixed(2)+'%';$('changeLabel').className=st.change>=0?'positive':'negative';$('openLabel').textContent=price(st.open,a.c);$('highLabel').textContent=price(st.high,a.c);$('lowLabel').textContent=price(st.low,a.c);$('volumeLabel').textContent=num(st.vol);$('favoriteAsset').textContent=state.watchlist.includes(a.s)?'★':'☆';$('favoriteAsset').classList.toggle('active',state.watchlist.includes(a.s));const badge=$('sourceBadge');badge.className='source-badge '+(src.mode==='live'?'live':src.mode==='delayed'?'delayed':'demo');badge.textContent=src.mode==='live'?'MARKET':src.mode==='delayed'?'DELAYED':'SIMULATED';$('marketStateLabel').textContent=marketStateText(a);$('dataSourceStat').textContent=src.source;$('updatedStat').textContent=relativeTime(src.updated);$('dayRangeStat').textContent=`${price(st.low,a.c)} — ${price(st.high,a.c)}`;$('yearRangeStat').textContent=`${price(st.low52,a.c)} — ${price(st.high52,a.c)}`;}
function marketStateText(a){if(a.type==='Crypto')return '24/7 market';const d=new Date(),day=d.getUTCDay();if(day===0||day===6)return 'Market may be closed';return 'Exchange hours vary';}
function relativeTime(t){const s=Math.max(0,Math.round((Date.now()-t)/1000));if(s<5)return 'just now';if(s<60)return `${s}s ago`;if(s<3600)return `${Math.floor(s/60)}m ago`;return `${Math.floor(s/3600)}h ago`;}
function renderAccount(){const m=metrics();$('cashMetric').textContent=money(state.cash);$('equityMetric').textContent=money(m.equity);$('unrealizedMetric').textContent=money(m.tradeUnreal+m.investUnreal);$('realizedMetric').textContent=money(state.realized);$('reservedMetric').textContent=money(m.reserved);$('buyingPower').textContent=money(Math.max(0,state.cash));$('unrealizedMetric').className=m.tradeUnreal+m.investUnreal>0?'positive':m.tradeUnreal+m.investUnreal<0?'negative':'';$('realizedMetric').className=state.realized>0?'positive':state.realized<0?'negative':'';renderHeader();}
function renderTicket(){$$('#modeSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));$('tradeTicket').classList.toggle('hidden',state.mode!=='trade');$('investTicket').classList.toggle('hidden',state.mode!=='invest');$$('#directionToggle button').forEach(b=>b.classList.toggle('active',b.dataset.side===state.tradeSide));$$('#investSideToggle button').forEach(b=>b.classList.toggle('active',b.dataset.side===state.investSide));$$('#tradeOrderTypes button').forEach(b=>b.classList.toggle('active',b.dataset.type===state.tradeOrderType));$$('#investOrderTypes button').forEach(b=>b.classList.toggle('active',b.dataset.type===state.investOrderType));$('tradeTriggerRow').classList.toggle('hidden',state.tradeOrderType==='market');$('investTriggerRow').classList.toggle('hidden',state.investOrderType==='market');const tb=$('tradeSubmit');tb.className='order-submit '+(state.tradeSide==='long'?'long':'short');tb.textContent=`Open ${state.tradeSide}`;const ib=$('investSubmit');ib.textContent=state.investSide==='buy'?'Buy investment':'Sell investment';renderTicketNumbers();}
function renderTicketNumbers(){const p=currentPrice(),margin=Number($('tradeAmount').value)||0,lev=Number($('tradeLeverage').value)||1,notional=margin*lev,qty=notional/Math.max(p,.000001),fee=notional*FEE_RATE;$('tradeQty').textContent=qty<1?qty.toFixed(5):qty.toFixed(3);$('tradeFee').textContent=money(fee);$('liquidationPreview').textContent=lev===1?'No leverage':`~${(95/lev).toFixed(1)}% adverse move`;const amt=Number($('investAmount').value)||0;$('investQty').textContent=(amt/Math.max(p,.000001)).toFixed(selected.type==='Crypto'?6:3);const h=currentHolding(selected.s);$('currentHolding').textContent=h?`${h.qty.toFixed(selected.type==='Crypto'?6:3)} ${selected.s}`:'None';$('investFee').textContent=money(amt*FEE_RATE);const canTrade=state.cash>=margin+fee&&margin>0;tbState($('tradeSubmit'),canTrade);const canInvest=state.investSide==='buy'?state.cash>=amt+amt*FEE_RATE:!!h&&h.qty>0;tbState($('investSubmit'),canInvest);}
function tbState(b,ok){b.disabled=!ok;}

function placeTrade(){const margin=Number($('tradeAmount').value)||0,leverage=Number($('tradeLeverage').value)||1,trigger=Number($('tradeTrigger').value)||currentPrice(),fee=margin*leverage*FEE_RATE;if(margin<=0)return ticketError('trade','Enter a margin amount.');if(state.cash<margin+fee)return noBuyingPower('trade');const order={id:uid(),kind:'trade',symbol:selected.s,side:state.tradeSide,type:state.tradeOrderType,trigger,margin,leverage,sl:$('slEnabled').checked?Number($('slValue').value)||0:null,tp:$('tpEnabled').checked?Number($('tpValue').value)||0:null,trail:$('trailEnabled').checked?Number($('trailValue').value)||0:null,created:Date.now()};if(order.type==='market')executeTrade(order,currentPrice());else{state.orders.push(order);state.history.push(hist('Order',selected.s,`${cap(order.side)} ${cap(order.type)} · ${money(margin)} margin`));ticketSuccess('trade',`${cap(order.type)} paper order queued.`);renderAll();save();}}
function executeTrade(o,market){const slip=market*SLIPPAGE*(o.side==='long'?1:-1),entry=market+slip,notional=o.margin*o.leverage,qty=notional/entry,fee=notional*FEE_RATE;if(state.cash<o.margin+fee)return;state.cash-=o.margin+fee;const dir=o.side==='long'?1:-1;state.positions.push({id:o.id||uid(),symbol:o.symbol,side:o.side,entry,qty,margin:o.margin,leverage:o.leverage,sl:o.sl?entry*(1-dir*o.sl/100):null,tp:o.tp?entry*(1+dir*o.tp/100):null,trailPct:o.trail||null,trailAnchor:entry,opened:Date.now()});state.history.push(hist('Trade opened',o.symbol,`${o.side.toUpperCase()} · ${o.leverage}× · ${qty.toFixed(3)} units`,-fee));toast('Paper trade opened',`${o.side.toUpperCase()} ${o.symbol} at ${price(entry,BY[o.symbol].c)}`,'success');ticketSuccess('trade','Paper position opened. No real order was sent.');renderAll();save();}
function placeInvestment(){const amount=Number($('investAmount').value)||0,trigger=Number($('investTrigger').value)||currentPrice();if(amount<=0)return ticketError('invest','Enter an amount.');const order={id:uid(),kind:'invest',symbol:selected.s,side:state.investSide,type:state.investOrderType,trigger,amount,created:Date.now()};if(order.type==='market')executeInvestment(order,currentPrice());else{if(order.side==='buy'&&state.cash<amount+amount*FEE_RATE)return noBuyingPower('invest');state.orders.push(order);state.history.push(hist('Order',selected.s,`${cap(order.side)} limit · ${money(amount)}`));ticketSuccess('invest','Limit paper order queued.');renderAll();save();}}
function executeInvestment(o,market){const a=BY[o.symbol],h=currentHolding(o.symbol);if(o.side==='buy'){const fee=o.amount*FEE_RATE;if(state.cash<o.amount+fee)return noBuyingPower('invest');const qty=o.amount/market;state.cash-=o.amount+fee;if(h){const cost=h.avg*h.qty+o.amount;h.qty+=qty;h.avg=cost/h.qty}else state.holdings.push({symbol:o.symbol,qty,avg:market,opened:Date.now()});state.history.push(hist('Investment buy',o.symbol,`${qty.toFixed(a.type==='Crypto'?6:3)} units at ${price(market,a.c)}`,-fee));if(!o.fromRecurring&&$('recurringEnabled').checked){state.recurring.push({symbol:o.symbol,amount:Number($('recurringAmount').value)||250,frequency:$('recurringFrequency').value,last:Date.now()});$('recurringEnabled').checked=false;$('recurringFields').classList.add('hidden');}toast('Paper investment added',`${o.symbol} · ${money(o.amount)}`,'success');}else{if(!h||h.qty<=0)return ticketError('invest','No holding to sell.');const requested=o.amount/market,qty=Math.min(h.qty,requested),gross=qty*market,fee=gross*FEE_RATE,pnl=(market-h.avg)*qty;state.cash+=gross-fee;h.qty-=qty;state.realized+=pnl-fee;if(h.qty<1e-9)state.holdings=state.holdings.filter(x=>x!==h);state.history.push(hist('Investment sell',o.symbol,`${qty.toFixed(a.type==='Crypto'?6:3)} units at ${price(market,a.c)}`,pnl-fee));toast('Paper investment sold',`${o.symbol} · ${money(gross-fee)}`,'success');}ticketSuccess('invest','Simulation updated. No real trade was sent.');renderAll();save();}
function closePosition(index,reason='Manual'){const p=state.positions[index];if(!p)return;const pnl=tradePnl(p),grossReturn=p.margin+pnl,exitFee=Math.max(0,p.qty*currentPrice(p.symbol)*FEE_RATE),credit=Math.max(0,grossReturn-exitFee);state.cash+=credit;state.realized+=pnl-exitFee;state.history.push(hist(reason==='Manual'?'Trade closed':reason,p.symbol,`${p.side.toUpperCase()} closed at ${price(currentPrice(p.symbol),BY[p.symbol].c)}`,pnl-exitFee));state.positions.splice(index,1);toast(reason==='Manual'?'Paper trade closed':reason,`${p.symbol} · ${money(pnl-exitFee)}`,pnl-exitFee>=0?'success':'error');renderAll();save();}
function ticketError(kind,msg){$(kind+'Message').textContent=msg;$(kind+'Message').className='ticket-message error';}
function ticketSuccess(kind,msg){$(kind+'Message').textContent=msg;$(kind+'Message').className='ticket-message success';setTimeout(()=>{if($(kind+'Message').textContent===msg){$(kind+'Message').textContent='';$(kind+'Message').className='ticket-message'}},3200);}
function noBuyingPower(kind){ticketError(kind,'Not enough paper buying power. Close a position, sell a holding, reduce the order, or reset the simulation.');checkDepleted(true);}
function hist(kind,symbol,detail,pnl=null){return{time:Date.now(),kind,symbol,detail,pnl}}
function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}

function renderActivity(){$$('#activityTabs button').forEach(b=>b.classList.toggle('active',b.dataset.pane===activePane));$('positionCount').textContent=state.positions.length;$('holdingCount').textContent=state.holdings.length;$('orderCount').textContent=state.orders.length;$('historyCount').textContent=state.history.length;if(activePane==='positions')renderPositions();if(activePane==='holdings')renderHoldings();if(activePane==='orders')renderOrders();if(activePane==='history')renderHistory();}
function table(headers,rows){return `<table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function renderPositions(){if(!state.positions.length){$('activityContent').innerHTML='<div class="empty-state">No open paper trades</div>';return}$('activityContent').innerHTML=table(['Symbol','Side','Entry','Last','Qty','Lev.','P&L','Stop','Target',''],state.positions.map((p,i)=>{const a=BY[p.symbol],pl=tradePnl(p);return[`<strong>${p.symbol}</strong>`,p.side.toUpperCase(),price(p.entry,a.c),price(currentPrice(p.symbol),a.c),p.qty.toFixed(3),p.leverage+'×',colored(pl),p.sl?price(p.sl,a.c):'—',p.tp?price(p.tp,a.c):'—',`<button class="row-action" data-close="${i}">Close</button>`]}));$$('[data-close]').forEach(b=>b.onclick=()=>closePosition(+b.dataset.close));}
function renderHoldings(){if(!state.holdings.length){$('activityContent').innerHTML='<div class="empty-state">No long-term paper investments</div>';return}$('activityContent').innerHTML=table(['Symbol','Average','Last','Units','Market value','P&L','Return'],state.holdings.map(h=>{const a=BY[h.symbol],pl=holdPnl(h),ret=pl/(h.avg*h.qty)*100;return[`<strong>${h.symbol}</strong>`,price(h.avg,a.c),price(currentPrice(h.symbol),a.c),h.qty.toFixed(a.type==='Crypto'?6:3),money(holdValue(h)),colored(pl),`<span class="${ret>=0?'positive':'negative'}">${ret>=0?'+':''}${ret.toFixed(2)}%</span>`]}));}
function renderOrders(){if(!state.orders.length){$('activityContent').innerHTML='<div class="empty-state">No open paper orders</div>';return}$('activityContent').innerHTML=table(['Symbol','Mode','Side','Type','Trigger','Amount','Created',''],state.orders.map((o,i)=>[`<strong>${o.symbol}</strong>`,o.kind==='trade'?'Trade':'Invest',o.side.toUpperCase(),cap(o.type),price(o.trigger,BY[o.symbol].c),money(o.kind==='trade'?o.margin:o.amount),new Date(o.created).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),`<button class="row-action" data-cancel="${i}">Cancel</button>`]));$$('[data-cancel]').forEach(b=>b.onclick=()=>{state.orders.splice(+b.dataset.cancel,1);renderAll();save()});}
function renderHistory(){if(!state.history.length){$('activityContent').innerHTML='<div class="empty-state">No simulation activity yet</div>';return}$('activityContent').innerHTML=table(['Time','Action','Symbol','Details','P&L'],state.history.slice().reverse().slice(0,120).map(h=>[new Date(h.time).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}),h.kind,`<strong>${h.symbol}</strong>`,escapeHtml(h.detail),h.pnl==null?'—':colored(h.pnl)]));}
function colored(v){return `<span class="${v>=0?'positive':'negative'}">${v>=0?'+':''}${money(v)}</span>`}

function tick(){
  let changed=false;
  ALL.forEach(a=>{if(sourceState[a.s].mode==='demo'){const d=series[a.s],last=d.at(-1),move=randn()*a.vol*.045,lastC=Math.max(.00001,last.c*(1+move));last.c=lastC;last.h=Math.max(last.h,lastC);last.l=Math.min(last.l,lastC);last.v+=Math.round(Math.random()*5000);changed=true;}});
  processOrders();processRisk();processRecurring();
  const m=metrics();if(Date.now()-lastEquitySample>12000){state.equityHistory.push({t:Date.now(),v:m.equity});if(state.equityHistory.length>360)state.equityHistory.shift();lastEquitySample=Date.now();save();}
  if(changed||state.view==='terminal'){renderInstrument();renderAccount();renderActivity();renderTicketNumbers();drawChart();}
  if(state.view==='home'){renderHome();drawHeroChart();}
  if(state.view==='portfolio')renderPortfolio();
  checkDepleted(false);
}
function processOrders(){for(let i=state.orders.length-1;i>=0;i--){const o=state.orders[i],p=currentPrice(o.symbol);let hit=false;if(o.type==='limit')hit=o.side==='long'||o.side==='buy'?p<=o.trigger:p>=o.trigger;if(o.type==='stop')hit=o.side==='long'?p>=o.trigger:p<=o.trigger;if(hit){state.orders.splice(i,1);if(o.kind==='trade')executeTrade(o,p);else executeInvestment(o,p);}}}
function processRisk(){for(let i=state.positions.length-1;i>=0;i--){const p=state.positions[i],cp=currentPrice(p.symbol),pl=tradePnl(p),dir=p.side==='long'?1:-1;if(p.trailPct){if((cp-p.trailAnchor)*dir>0)p.trailAnchor=cp;const trail=p.trailAnchor*(1-dir*p.trailPct/100);if((cp-trail)*dir<=0){closePosition(i,'Trailing stop');continue}}if(p.sl&&((cp-p.sl)*dir<=0)){closePosition(i,'Stop loss');continue}if(p.tp&&((cp-p.tp)*dir>=0)){closePosition(i,'Take profit');continue}if(pl<=-p.margin*.95){closePosition(i,'Auto-liquidated');continue}}}
function processRecurring(){const now=Date.now(),period={daily:86400000,weekly:604800000,monthly:2592000000};state.recurring.forEach(r=>{if(now-r.last>=period[r.frequency]){const p=currentPrice(r.symbol),fee=r.amount*FEE_RATE;if(state.cash>=r.amount+fee){executeInvestment({symbol:r.symbol,side:'buy',amount:r.amount,fromRecurring:true},p);r.last=now}else r.last=now;}})}
function checkDepleted(force){const m=metrics(),hasAssets=state.holdings.length||state.positions.length,canSpend=state.cash>10;if(!canSpend&&!hasAssets&&(force||m.equity<=10)&&!depletedShown){depletedShown=true;$('depletedText').textContent='Your simulated account has no meaningful buying power or assets left. Nothing real was lost. Restart the paper account whenever you want.';$('depletedOverlay').classList.remove('hidden');}if(canSpend||hasAssets)depletedShown=false;}
function resetAccount(amount=100000,ask=false){if(ask&&!confirm('Reset the paper account, positions, holdings, orders, journal and performance history?'))return;const keepView=state.view;Object.assign(state,structuredClone(defaults));state.cash=amount;state.startBalance=amount;state.equityHistory=[{t:Date.now(),v:amount}];state.view=keepView==='home'?'home':'terminal';selected=BY.NVDA;depletedShown=false;$('depletedOverlay').classList.add('hidden');closeSettings();renderAll();save();toast('Paper account reset',`Virtual starting balance: ${money(amount)}`,'success');}

function setupCanvases(){['chartCanvas','heroChart','allocationCanvas','equityCanvas'].forEach(id=>{const c=$(id);if(!c)return;const r=c.getBoundingClientRect();if(r.width<2||r.height<2)return;const dpr=Math.min(2,window.devicePixelRatio||1);c.width=Math.round(r.width*dpr);c.height=Math.round(r.height*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);c._cssW=r.width;c._cssH=r.height;});}
function chartData(){let d=(series[selected.s]||[]).slice(-settings.bars);if(settings.chartType==='heikin')d=heikin(d);return d;}
function heikin(data){let prevO=data[0]?.o||0,prevC=data[0]?.c||0;return data.map((d,i)=>{const c=(d.o+d.h+d.l+d.c)/4,o=i?(prevO+prevC)/2:(d.o+d.c)/2,h=Math.max(d.h,o,c),l=Math.min(d.l,o,c);prevO=o;prevC=c;return{...d,o,h,l,c}})}
function drawChart(){const c=$('chartCanvas');if(!c||!c._cssW)return;const ctx=c.getContext('2d'),W=c._cssW,H=c._cssH,data=chartData();ctx.clearRect(0,0,W,H);if(data.length<2){$('chartEmpty').classList.remove('hidden');return}$('chartEmpty').classList.add('hidden');const left=12,right=68,top=14,bottom=20,volOn=settings.indicators.volume,rsiOn=settings.indicators.rsi,macdOn=settings.indicators.macd;const volH=volOn?Math.min(88,H*.16):0,rsiH=rsiOn?70:0,macdH=macdOn?70:0,mainBottom=H-bottom-volH-rsiH-macdH-(volOn?8:0)-(rsiOn?8:0)-(macdOn?8:0);let lo=Math.min(...data.map(d=>d.l)),hi=Math.max(...data.map(d=>d.h));const pad=(hi-lo||1)*.08;lo-=pad;hi+=pad;const step=(W-left-right)/data.length,x=i=>left+(i+.5)*step,y=v=>top+(hi-v)/(hi-lo)*(mainBottom-top);if(settings.grid){ctx.strokeStyle='rgba(255,255,255,.045)';ctx.lineWidth=1;for(let i=0;i<=5;i++){const yy=top+i*(mainBottom-top)/5;ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(W-right,yy);ctx.stroke()}for(let i=0;i<=6;i++){const xx=left+i*(W-left-right)/6;ctx.beginPath();ctx.moveTo(xx,top);ctx.lineTo(xx,mainBottom);ctx.stroke()}}
  ctx.font='8px system-ui';ctx.fillStyle='#66717d';ctx.textAlign='left';for(let i=0;i<=5;i++){const val=hi-i*(hi-lo)/5;ctx.fillText(axis(val),W-right+7,top+i*(mainBottom-top)/5+3)}
  if(settings.chartType==='line'||settings.chartType==='area'){const vals=data.map(d=>d.c);if(settings.chartType==='area'){const grad=ctx.createLinearGradient(0,top,0,mainBottom);grad.addColorStop(0,alpha(settings.up,.18));grad.addColorStop(1,alpha(settings.up,0));ctx.beginPath();vals.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.lineTo(x(vals.length-1),mainBottom);ctx.lineTo(x(0),mainBottom);ctx.closePath();ctx.fillStyle=grad;ctx.fill()}line(ctx,vals,x,y,'#cfd5dc',1.4)}else{const body=Math.max(1,Math.min(9,step*.62));data.forEach((d,i)=>{const xx=x(i),up=d.c>=d.o,col=up?settings.up:settings.down;ctx.strokeStyle=col;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(xx,y(d.h));ctx.lineTo(xx,y(d.l));ctx.stroke();if(settings.chartType==='bars'){ctx.beginPath();ctx.moveTo(xx-body/2,y(d.o));ctx.lineTo(xx,y(d.o));ctx.moveTo(xx,y(d.c));ctx.lineTo(xx+body/2,y(d.c));ctx.stroke()}else{const yy=Math.min(y(d.o),y(d.c)),hh=Math.max(1,Math.abs(y(d.c)-y(d.o)));ctx.strokeStyle=col;if(settings.chartType==='hollow'&&up){ctx.strokeRect(xx-body/2,yy,body,hh)}else{ctx.fillStyle=col;ctx.fillRect(xx-body/2,yy,body,hh)}}})}
  const closes=data.map(d=>d.c);if(settings.indicators.sma)line(ctx,sma(closes,20),x,y,'#e8bf62',1.1);if(settings.indicators.sma50)line(ctx,sma(closes,50),x,y,'#a78bfa',1.1);if(settings.indicators.ema)line(ctx,ema(closes,20),x,y,'#6cc7d9',1.1);if(settings.indicators.vwap)line(ctx,vwap(data),x,y,'#d984c6',1.05);if(settings.indicators.bb){const bb=boll(closes,20);line(ctx,bb.upper,x,y,'rgba(122,162,247,.7)',1);line(ctx,bb.lower,x,y,'rgba(122,162,247,.7)',1)}
  let paneY=mainBottom+8;if(volOn){const vh=volH-8,mv=Math.max(...data.map(d=>d.v||0),1);data.forEach((d,i)=>{const h=(d.v||0)/mv*vh;ctx.fillStyle=d.c>=d.o?alpha(settings.up,.28):alpha(settings.down,.28);ctx.fillRect(x(i)-Math.max(1,step*.3),paneY+vh-h,Math.max(1,step*.6),h)});ctx.fillStyle='#59636f';ctx.fillText('VOL',left,paneY+8);paneY+=volH+8}
  if(rsiOn){const vals=rsi(closes,14),rh=rsiH-8,ry=v=>paneY+(100-v)/100*rh;ctx.strokeStyle='rgba(255,255,255,.045)';[30,50,70].forEach(v=>{ctx.beginPath();ctx.moveTo(left,ry(v));ctx.lineTo(W-right,ry(v));ctx.stroke()});line(ctx,vals,x,ry,'#9f8cff',1.2);ctx.fillStyle='#59636f';ctx.fillText('RSI 14',left,paneY+8);paneY+=rsiH+8}
  if(macdOn){const m=macd(closes),vals=[...m.macd,...m.signal].filter(Number.isFinite),mn=Math.min(...vals,0),mx=Math.max(...vals,0),span=mx-mn||1,mh=macdH-8,my=v=>paneY+(mx-v)/span*mh;ctx.strokeStyle='rgba(255,255,255,.045)';ctx.beginPath();ctx.moveTo(left,my(0));ctx.lineTo(W-right,my(0));ctx.stroke();line(ctx,m.macd,x,my,'#6cc7d9',1);line(ctx,m.signal,x,my,'#e8bf62',1);ctx.fillStyle='#59636f';ctx.fillText('MACD',left,paneY+8)}
  const last=data.at(-1),yy=y(last.c),col=last.c>=last.o?settings.up:settings.down;ctx.fillStyle=col;ctx.fillRect(W-right,yy-9,right-5,18);ctx.fillStyle='#08100c';ctx.font='700 8px system-ui';ctx.fillText(axis(last.c),W-right+6,yy+3);if(hoverIndex!=null&&settings.crosshair){const i=clamp(hoverIndex,0,data.length-1),d=data[i],xx=x(i),cy=y(d.c);ctx.strokeStyle='rgba(220,226,232,.28)';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(xx,top);ctx.lineTo(xx,H-bottom);ctx.moveTo(left,cy);ctx.lineTo(W-right,cy);ctx.stroke();ctx.setLineDash([])}
}
function chartHover(e){if(!settings.crosshair)return;const c=e.currentTarget,r=c.getBoundingClientRect(),data=chartData(),left=12,right=68,step=(r.width-left-right)/data.length,i=clamp(Math.floor((e.clientX-r.left-left)/step),0,data.length-1),d=data[i];hoverIndex=i;$('ohlcLegend').textContent=`O ${axis(d.o)}  H ${axis(d.h)}  L ${axis(d.l)}  C ${axis(d.c)}`;const tip=$('crosshairInfo');tip.innerHTML=`<strong>${selected.s}</strong> · ${new Date(d.t).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}<br>O ${axis(d.o)} &nbsp; H ${axis(d.h)} &nbsp; L ${axis(d.l)} &nbsp; C ${axis(d.c)} &nbsp; Vol ${num(d.v)}`;tip.style.left=Math.min(e.clientX-r.left+12,r.width-250)+'px';tip.style.top=Math.max(8,e.clientY-r.top-45)+'px';tip.classList.remove('hidden');drawChart();}
function axis(v){if(v>=10000)return v.toLocaleString(undefined,{maximumFractionDigits:0});if(v<1)return v.toFixed(4);return v.toFixed(2)}
function alpha(hex,a){if(!/^#[0-9a-f]{6}$/i.test(hex))return hex;const n=parseInt(hex.slice(1),16);return`rgba(${n>>16},${n>>8&255},${n&255},${a})`}
function line(ctx,vals,x,y,color,w=1){ctx.strokeStyle=color;ctx.lineWidth=w;ctx.beginPath();let started=false;vals.forEach((v,i)=>{if(v==null||!Number.isFinite(v))return;started?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v));started=true});ctx.stroke()}
function sma(vals,n){return vals.map((_,i)=>i<n-1?null:vals.slice(i-n+1,i+1).reduce((a,b)=>a+b,0)/n)}
function ema(vals,n){const k=2/(n+1),out=[];let e=null;vals.forEach(v=>{e=e==null?v:v*k+e*(1-k);out.push(e)});return out}
function vwap(data){let pv=0,v=0;return data.map(d=>{pv+=((d.h+d.l+d.c)/3)*(d.v||1);v+=d.v||1;return pv/v})}
function boll(vals,n){const mid=sma(vals,n),upper=[],lower=[];vals.forEach((_,i)=>{if(i<n-1){upper.push(null);lower.push(null);return}const arr=vals.slice(i-n+1,i+1),m=mid[i],sd=Math.sqrt(arr.reduce((s,x)=>s+(x-m)**2,0)/n);upper.push(m+2*sd);lower.push(m-2*sd)});return{upper,lower}}
function rsi(vals,n=14){const out=Array(vals.length).fill(null);if(vals.length<=n)return out;let g=0,l=0;for(let i=1;i<=n;i++){const d=vals[i]-vals[i-1];if(d>=0)g+=d;else l-=d}g/=n;l/=n;out[n]=100-100/(1+(l===0?100:g/l));for(let i=n+1;i<vals.length;i++){const d=vals[i]-vals[i-1];g=(g*(n-1)+Math.max(d,0))/n;l=(l*(n-1)+Math.max(-d,0))/n;out[i]=100-100/(1+(l===0?100:g/l))}return out}
function macd(vals){const e12=ema(vals,12),e26=ema(vals,26),m=vals.map((_,i)=>e12[i]-e26[i]),s=ema(m,9);return{macd:m,signal:s}}
function drawHeroChart(){const c=$('heroChart');if(!c||!c._cssW)return;const ctx=c.getContext('2d'),W=c._cssW,H=c._cssH,d=(series[selected.s]||[]).slice(-70),vals=d.map(x=>x.c),lo=Math.min(...vals),hi=Math.max(...vals),sp=hi-lo||1,x=i=>8+i*(W-16)/(vals.length-1),y=v=>10+(hi-v)/sp*(H-20);ctx.clearRect(0,0,W,H);ctx.strokeStyle='rgba(255,255,255,.045)';for(let i=1;i<4;i++){const yy=i*H/4;ctx.beginPath();ctx.moveTo(0,yy);ctx.lineTo(W,yy);ctx.stroke()}const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,alpha(settings.up,.15));g.addColorStop(1,alpha(settings.up,0));ctx.beginPath();vals.forEach((v,i)=>i?ctx.lineTo(x(i),y(v)):ctx.moveTo(x(i),y(v)));ctx.lineTo(x(vals.length-1),H);ctx.lineTo(x(0),H);ctx.closePath();ctx.fillStyle=g;ctx.fill();line(ctx,vals,x,y,'#cbd2da',1.4);}

function renderPortfolio(){const m=metrics();$('portfolioEquity').textContent=money(m.equity);$('portfolioCash').textContent=money(state.cash);$('investedKpi').textContent=money(m.investedCost);$('tradingPnlKpi').textContent=money(state.realized+m.tradeUnreal);$('tradingPnlKpi').className=state.realized+m.tradeUnreal>=0?'positive':'negative';$('investPnlKpi').textContent=money(m.investUnreal);$('investPnlKpi').className=m.investUnreal>=0?'positive':'negative';$('openOrdersKpi').textContent=state.orders.length;$('recurringCount').textContent=`${state.recurring.length} recurring plan${state.recurring.length===1?'':'s'}`;if(!state.holdings.length)$('portfolioHoldings').innerHTML='<div class="empty-state" style="min-height:130px">No long-term paper holdings yet</div>';else $('portfolioHoldings').innerHTML=table(['Asset','Average cost','Last','Units','Cost basis','Market value','P&L','Return'],state.holdings.map(h=>{const a=BY[h.symbol],pl=holdPnl(h),ret=pl/(h.avg*h.qty)*100;return[`<strong>${h.symbol}</strong><br><span class="muted">${escapeHtml(a.n)}</span>`,price(h.avg,a.c),price(currentPrice(h.symbol),a.c),h.qty.toFixed(a.type==='Crypto'?6:3),money(h.avg*h.qty),money(holdValue(h)),colored(pl),`<span class="${ret>=0?'positive':'negative'}">${ret>=0?'+':''}${ret.toFixed(2)}%</span>`]}));setTimeout(()=>{setupCanvases();renderPortfolioCharts()},0);}
function renderPortfolioCharts(){drawAllocation();drawEquity()}
function drawAllocation(){const c=$('allocationCanvas');if(!c||!c._cssW)return;const ctx=c.getContext('2d'),W=c._cssW,H=c._cssH,vals=state.holdings.map(h=>({s:h.symbol,v:holdValue(h)})).filter(x=>x.v>0),total=vals.reduce((s,x)=>s+x.v,0);ctx.clearRect(0,0,W,H);const cx=W/2,cy=H/2,r=Math.min(W,H)*.40,inner=r*.64;if(!total){ctx.strokeStyle='#28313b';ctx.lineWidth=r-inner;ctx.beginPath();ctx.arc(cx,cy,(r+inner)/2,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#697481';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText('No holdings',cx,cy+3);$('allocationLegend').innerHTML='';return}let start=-Math.PI/2;vals.forEach((v,i)=>{const ang=v.v/total*Math.PI*2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,start,start+ang);ctx.closePath();ctx.fillStyle=COLORS[i%COLORS.length];ctx.fill();start+=ang});ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(cx,cy,inner,0,Math.PI*2);ctx.fill();ctx.globalCompositeOperation='source-over';ctx.fillStyle='#d4dae1';ctx.font='700 11px system-ui';ctx.textAlign='center';ctx.fillText(money(total),cx,cy+4);$('allocationLegend').innerHTML=vals.map((v,i)=>`<div class="legend-row"><i class="legend-dot" style="background:${COLORS[i%COLORS.length]}"></i><span>${v.s}</span><strong>${(v.v/total*100).toFixed(1)}%</strong></div>`).join('');}
function drawEquity(){const c=$('equityCanvas');if(!c||!c._cssW)return;const ctx=c.getContext('2d'),W=c._cssW,H=c._cssH,d=state.equityHistory.length>1?state.equityHistory:[{t:Date.now()-1,v:state.startBalance},{t:Date.now(),v:metrics().equity}],vals=d.map(x=>x.v),lo=Math.min(...vals),hi=Math.max(...vals),sp=hi-lo||1,pad=18,x=i=>pad+i*(W-pad*2)/(d.length-1),y=v=>pad+(hi-v)/sp*(H-pad*2);ctx.clearRect(0,0,W,H);ctx.strokeStyle='rgba(255,255,255,.05)';for(let i=0;i<5;i++){const yy=pad+i*(H-pad*2)/4;ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(W-pad,yy);ctx.stroke()}line(ctx,vals,x,y,vals.at(-1)>=state.startBalance?settings.up:settings.down,1.6);ctx.fillStyle='#687381';ctx.font='8px system-ui';ctx.fillText(money(hi),pad,10);ctx.fillText(money(lo),pad,H-4);}

function populateJournal(){$('journalAsset').innerHTML=ALL.map(a=>`<option value="${a.s}">${a.s} — ${escapeHtml(a.n)}</option>`).join('')}
function saveJournal(){const text=$('journalText').value.trim();if(!text)return;state.journal.unshift({time:Date.now(),symbol:$('journalAsset').value,tag:$('journalTag').value,text});$('journalText').value='';renderJournal();save();toast('Journal entry saved','Added to your local simulation journal.','success')}
function renderJournal(){if(!state.journal.length){$('journalList').innerHTML='<div class="empty-state" style="min-height:220px">No journal entries yet</div>';return}$('journalList').innerHTML=state.journal.map(j=>`<article class="journal-entry"><div class="journal-entry-head"><strong>${escapeHtml(j.symbol)} · ${escapeHtml(j.tag)}</strong><span>${new Date(j.time).toLocaleString()}</span></div><p>${escapeHtml(j.text)}</p></article>`).join('')}

const TUTORIAL=[
  {tag:'STEP 1 OF 6',title:'This is a simulation.',body:'Every balance, order, position and profit/loss figure in Tickrift is virtual. There are no deposits, no withdrawals and no connection to a brokerage account.',a:'Paper account',b:'Starts with virtual cash',c:'Real money',d:'Never used'},
  {tag:'STEP 2 OF 6',title:'Trade and Invest are separate.',body:'Trade is for short-term paper positions. You can go long or short and use simulated leverage. Invest is for long-term holdings with buy/sell orders, average cost and allocation tracking.',a:'Trade',b:'Long, short, stops, leverage',c:'Invest',d:'Holdings, cost basis, allocation'},
  {tag:'STEP 3 OF 6',title:'Read the data badge.',body:'Each instrument shows whether its price feed is MARKET, DELAYED or SIMULATED. A live provider can supply stocks, ETFs and indices. Crypto can use a market-linked public feed when available.',a:'MARKET / DELAYED',b:'Provider-linked data',c:'SIMULATED',d:'Generated practice prices'},
  {tag:'STEP 4 OF 6',title:'Use order types deliberately.',body:'Market orders fill at the displayed paper price plus a small simulated slippage. Limit and stop orders wait for their trigger. Stop-loss and take-profit only manage the simulated position.',a:'Market',b:'Paper fill now',c:'Limit / Stop',d:'Wait for a trigger'},
  {tag:'STEP 5 OF 6',title:'Leverage can liquidate a paper trade.',body:'Leveraged positions reserve virtual margin. If a paper trade loses about 95% of its reserved margin, Tickrift auto-liquidates it so the simulation does not create unlimited negative cash.',a:'Margin',b:'Virtual cash reserved',c:'Auto-liquidation',d:'Simulation risk control'},
  {tag:'STEP 6 OF 6',title:'Running out of paper money is reversible.',body:'If the account has no usable cash or assets left, Tickrift offers a fresh paper account. Nothing real was lost. You can restart with $100,000 or try a $10,000 challenge.',a:'Restart',b:'Fresh paper balance',c:'Journal',d:'Review what went wrong'}
];
function openTutorial(step=0){tutorialStep=step;$('tutorialOverlay').classList.remove('hidden');renderTutorial()}
function closeTutorial(){$('tutorialOverlay').classList.add('hidden')}
function renderTutorial(){const t=TUTORIAL[tutorialStep];$('tutorialProgress').innerHTML=TUTORIAL.map((_,i)=>`<i class="${i<=tutorialStep?'active':''}"></i>`).join('');$('tutorialContent').innerHTML=`<span class="tutorial-step-tag">${t.tag}</span><h3>${t.title}</h3><p>${t.body}</p><div class="tutorial-example"><div><span>${t.a}</span><strong>${t.b}</strong></div><div><span>${t.c}</span><strong>${t.d}</strong></div></div>`;$('tutorialPrev').disabled=tutorialStep===0;$('tutorialNext').textContent=tutorialStep===TUTORIAL.length-1?'Start simulator':'Next';if(tutorialStep===TUTORIAL.length-1)$('tutorialNext').onclick=()=>{state.tutorialSeen=true;save();closeTutorial();enterMode('trade')};else $('tutorialNext').onclick=()=>{tutorialStep++;renderTutorial()};}
function toast(title,msg,type=''){const node=document.createElement('div');node.className='toast '+type;node.innerHTML=`<strong>${escapeHtml(title)}</strong>${escapeHtml(msg)}`;$('toastHost').appendChild(node);setTimeout(()=>node.remove(),3600)}

function providerInterval(){return({'1m':'1min','5m':'5min','15m':'15min','1h':'1h','4h':'4h','1D':'1day','1W':'1week'})[settings.timeframe]||'5min'}
async function startFeeds(){externalEndpoint=(window.TICKRIFT_CONFIG?.marketDataEndpoint||'').trim().replace(/\/$/,'');if(window.TICKRIFT_CONFIG?.directCrypto!==false){await pollCryptoPrices();cryptoTimer=setInterval(pollCryptoPrices,45000)}if(externalEndpoint){const ok=await pollExternalSnapshot();if(ok){await loadExternalHistory(selected.s);externalTimer=setInterval(async()=>{await pollExternalSnapshot();renderAll()},12000)}}renderAll();}
async function pollCryptoPrices(){const coins=ASSETS.crypto.map(a=>a.cgid).join(',');try{const res=await fetch(`${CG_BASE}/simple/price?ids=${encodeURIComponent(coins)}&vs_currencies=usd&include_24hr_change=true&include_last_updated_at=true`,{cache:'no-store'});if(!res.ok)throw new Error('crypto');const payload=await res.json();ASSETS.crypto.forEach(a=>{const q=payload[a.cgid];if(!q?.usd)return;const p=Number(q.usd),d=series[a.s],last=d.at(-1);last.c=p;last.h=Math.max(last.h,p);last.l=Math.min(last.l,p);sourceState[a.s]={mode:'live',source:'CoinGecko',updated:(q.last_updated_at||Date.now()/1000)*1000,delay:null};});if(window.TICKRIFT_CONFIG?.cryptoAttribution!==false)$('footerData').innerHTML='Crypto data: <a href="https://www.coingecko.com/en/api" target="_blank" rel="noopener">CoinGecko</a>. Other instruments show their source in the terminal.';renderAll();}catch{/* keep simulation */}}
async function loadCryptoHistory(a){if(!a.cgid||window.TICKRIFT_CONFIG?.directCrypto===false)return false;try{const spec=cryptoRangeSpec(settings.timeframe),url=`${CG_BASE}/coins/${encodeURIComponent(a.cgid)}/market_chart?vs_currency=usd&days=${spec.days}`;const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error('history');const p=(await res.json()).prices;if(!Array.isArray(p)||p.length<5)return false;series[a.s]=aggregatePrices(p,spec.bucketMs).slice(-320);sourceState[a.s]={mode:'live',source:'CoinGecko',updated:Date.now(),delay:null};return true}catch{return false}}
function cryptoRangeSpec(tf){return tf==='1m'?{days:1,bucketMs:5*60000}:tf==='5m'?{days:1,bucketMs:5*60000}:tf==='15m'?{days:3,bucketMs:15*60000}:tf==='1h'?{days:14,bucketMs:3600000}:tf==='4h'?{days:60,bucketMs:4*3600000}:tf==='1D'?{days:365,bucketMs:86400000}:{days:730,bucketMs:7*86400000}}
function aggregatePrices(points,bucket){const bins=new Map();points.forEach(([t,p])=>{const k=Math.floor(t/bucket)*bucket;if(!bins.has(k))bins.set(k,[]);bins.get(k).push(Number(p))});return [...bins.entries()].sort((a,b)=>a[0]-b[0]).map(([t,v])=>({t,o:v[0],h:Math.max(...v),l:Math.min(...v),c:v.at(-1),v:0}))}
async function pollExternalSnapshot(){if(!externalEndpoint)return false;try{const wanted=[selected.s,...state.watchlist,...state.holdings.map(h=>h.symbol),...state.positions.map(p=>p.symbol),'NVDA','AAPL','MSFT','SPX','SPY'];const symbols=[...new Set(wanted)].filter(s=>BY[s]&&BY[s].type!=='Crypto').slice(0,20).join(','),res=await fetch(`${externalEndpoint}/snapshot?symbols=${encodeURIComponent(symbols)}`,{cache:'no-store',headers:{Accept:'application/json'}});if(!res.ok)throw new Error('feed');const payload=await res.json();if(!payload?.quotes)throw new Error('feed');Object.entries(payload.quotes).forEach(([s,q])=>{if(!BY[s]||!Number(q.price))return;const d=series[s],p=Number(q.price),last=d.at(-1);last.c=p;last.h=Math.max(last.h,p);last.l=Math.min(last.l,p);if(Number(q.volume)>=0)last.v=Number(q.volume);sourceState[s]={mode:q.delayed?'delayed':'live',source:q.source||payload.source||'Market provider',updated:Number(q.timestamp)||Date.now(),delay:q.delayed||null};});return true}catch{return false}}
async function loadExternalHistory(symbol){if(!externalEndpoint)return false;try{const res=await fetch(`${externalEndpoint}/history?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(providerInterval())}&limit=320`,{cache:'no-store',headers:{Accept:'application/json'}});if(!res.ok)throw new Error('history');const payload=await res.json(),raw=payload?.candles;if(!Array.isArray(raw)||raw.length<2)return false;const d=raw.map(x=>({t:Number(x.time??x.t),o:Number(x.open??x.o),h:Number(x.high??x.h),l:Number(x.low??x.l),c:Number(x.close??x.c),v:Number(x.volume??x.v??0)})).filter(x=>[x.t,x.o,x.h,x.l,x.c].every(Number.isFinite));if(d.length<2)return false;series[symbol]=d.sort((a,b)=>a.t-b.t).slice(-320);sourceState[symbol]={mode:payload.delayed?'delayed':'live',source:payload.source||'Market provider',updated:Date.now(),delay:payload.delayed||null};return true}catch{return false}}
async function loadSelectedMarketHistory(){if(selected.type==='Crypto'){await loadCryptoHistory(selected);return}if(externalEndpoint)await loadExternalHistory(selected.s);}

init();
})();
